spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          password: 5EYcHss4
          username: root
          url: jdbc:mysql://121.36.136.81/t1?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        slave_1:
          password: 5EYcHss4
          username: root
          url: jdbc:mysql://121.36.136.81/t2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
mybatis-plus:
  configuration:
    #驼峰转下滑线
    map-underscore-to-camel-case: true
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml